# Backend configuration
backend:
  image: 307711586773.dkr.ecr.us-east-1.amazonaws.com/employee-backend
  tag: be-dev-20260723-175850
  replicas: 2
  port: 5000

# Frontend configuration
frontend:
  image: 307711586773.dkr.ecr.us-east-1.amazonaws.com/employee-frontend
  tag: fe-dev-20260723-175850
  replicas: 2
  port: 80

# Service Account for S3 + Secrets Manager access
serviceAccount:
  name: app-sa
  roleArn: "arn:aws:iam::307711586773:role/landmark-cluster-dev-app-sa"

# External Secrets - AWS Secrets Manager
externalSecrets:
  secretName: "landmark-cluster-dev/employee-app"
  refreshInterval: "1m"

# Ingress via ALB
ingress:
  enabled: true
  ingressClass: alb

# S3 bucket
s3:
  bucket: "landmarkdevops-app-bucket-dev"
  region: "us-east-1"

# CloudWatch Logging
logging:
  logGroup: "/landmark/employee-app"
  environment: "dev"

# Monitoring - kube-prometheus-stack
monitoring:
  enabled: true

kube-prometheus-stack:
  alertmanager:
    enabled: false
  grafana:
    adminPassword: admin123
    service:
      type: LoadBalancer
      loadBalancerClass: service.k8s.aws/nlb
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: ALL
    additionalDataSources:
      - name: CloudWatch
        type: cloudwatch
        uid: cloudwatch
        access: proxy
        jsonData:
          authType: default
          defaultRegion: us-east-1
          logGroups:
            - arn: "arn:aws:logs:us-east-1:307711586773:log-group:/landmark/employee-app"
              name: /landmark/employee-app
    serviceAccount:
      create: true
      name: employee-app-grafana
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::307711586773:role/landmark-cluster-dev-app-sa"
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      retention: 7d
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp2
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
  nodeExporter:
    enabled: true
  kubeStateMetrics:
    enabled: true
