# Backend configuration
backend:
  image: 075120018043.dkr.ecr.us-east-1.amazonaws.com/employee-backend
  tag: be-dev-20260710-000417
  replicas: 2
  port: 5000

# Frontend configuration
frontend:
  image: 075120018043.dkr.ecr.us-east-1.amazonaws.com/employee-frontend
  tag: fe-dev-20260710-000417
  replicas: 2
  port: 80

# Service Account for S3 + Secrets Manager access
serviceAccount:
  name: app-sa
  roleArn: "arn:aws:iam::075120018043:role/landmark-cluster-dev-app-sa"

# External Secrets - AWS Secrets Manager
externalSecrets:
  secretName: "landmark-cluster-dev/employee-app"
  refreshInterval: "1m"

# Ingress via ALB
ingress:
  enabled: true
  ingressClass: alb

# S3 bucket
s3:
  bucket: "landmark-app-bucket-dev"
  region: "us-east-1"

# CloudWatch Logging
logging:
  logGroup: "/landmark/employee-app"
  environment: "dev"

# Monitoring - kube-prometheus-stack
monitoring:
  enabled: true

kube-prometheus-stack:
  alertmanager:
    enabled: false
  grafana:
    adminPassword: admin123
    service:
      type: LoadBalancer
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      retention: 7d
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp2
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
  nodeExporter:
    enabled: true
  kubeStateMetrics:
    enabled: true
